import Footer from "@/components/footer";
import "./globals.css";
import Header from "@/components/header";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div style={{ height: "85vh" }}>{children}</div>
        <ToastContainer position="top-center" closeOnClick theme="dark"/>
        <Footer />
      </body>
    </html>
  );
}
